aulaapp/apps/clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.list_clients, name='list_clients'),
    path('adicionar/', views.add_client, name='add_client'),
    path('editar/<int:id_client>/', views.edit_client, name='edit_client'),
    path('excluir/<int:id_client>/', views.delete_client, name='delete_client'),
    path('buscar/', views.search_clients, name='search_clients'),
]

aulaapp/apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('adicionar/<int:id_client>/', views.add_order, name='add_order'),
    path('excluir/<int:id_order>/', views.delete_order, name='delete_order'),
    path('excluir-item/<int:id_order_item>/', views.delete_order_item, name='delete_order_item'),
    path('adicionar-item/<int:id_order>/', views.add_order_item, name='add_order_item'),
    path('editar-status/<int:id_order>/', views.edit_order_status, name='edit_order_status'),
]

aulaapp/aulaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('redessociais/', include('socialnetworks.urls', namespace='socialnetworks')),
    path('produtos/', include('products.urls', namespace='products')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('pedidos/', include('orders.urls', namespace='orders')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aulaapp/apps/orders/models.py
from django.db import models
from products.models import Product
from clients.models import Client

# Create your models here.

class Order(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    total_price = models.FloatField('Preco Total', null=True, blank=True, default=0.0)
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    order_item = models.ManyToManyField(Product, through='OrderItem', blank=True)
    
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering =['-created_on']

    def __str__(self):
        return "%s" % (self.total_price) 


class OrderItem(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField('Quantidade',null=True, blank=True,default=0)
    unitary_price = models.FloatField('Preco unitario',null=True, blank=True, default=0.0)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de pedido'
        verbose_name_plural = 'Itens de pedido'
        ordering =['id']

    def __str__(self):
        return "%s" % (self.quantity) 

aulaapp/apps/orders/forms.py
from django import forms
from .models import Order, Client, OrderItem ,Product

class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        exclude = ('client', 'created_on' , 'updated_on')

class OrderItemForm(forms.ModelForm):
    
    class Meta:
        model = OrderItem
        exclude = ('order', 'created_on' , 'updated_on')

aulaapp/apps/orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import OrderForm, OrderItemForm
from .models import Order , OrderItem, Product, Client
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/contas/login/')
def add_order(request, id_client):
    template_name = 'orders/add_order.html'
    context = {}
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.client = Client.objects.get(id=id_client)
            f.save()
            form.save_m2m()
            return redirect('orders:list_orders')
    form = OrderForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_orders(request):
    template_name = 'orders/list_orders.html'
    orders = Order.objects.filter()
    order_items = OrderItem.objects.filter()
    products = Product.objects.filter()
    clients = Client.objects.filter()
    context = {
        'orders': orders,
        'order_items': order_items,
        'products': products,
        'clients': clients
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_order(request, id_order):
    order = Order.objects.get(id=id_order)
    order.delete()
    return redirect('orders:list_orders')

@login_required(login_url='/contas/login/')
def add_order_item(request, id_order):
    template_name = 'orders/add_order_item.html'
    context = {}
    if request.method == 'POST':
        form = OrderItemForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.order = Order.objects.get(id=id_order)
            f.save()
            form.save_m2m()
            return redirect('orders:list_orders')
    form = OrderItemForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_order_item(request, id_order_item):
    orderitem = OrderItem.objects.get(id=id_order_item)
    orderitem.delete()
    return redirect('orders:list_orders')

@login_required(login_url='/contas/login/')
def edit_order_status(request, id_order):
    template_name = 'orders/edit_order_status.html'
    context ={}
    order = get_object_or_404(Order, id=id_order)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('orders:list_orders')
    form = OrderForm(instance=order)
    context['form'] = form
    return render(request, template_name, context)

aulaapp/templates/orders/add_order.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Pedido - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Deseja abrir um pedido? </b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm">Sim</button>   <a href="{% url 'clients:list_clients' %}" class="btn btn-primary btn-sm">Nao</a>     
                </form>
                
            </div>
        </div>
    </div>

{% endblock body %}

aulaapp/templates/orders/add_order_item.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Item de Pedido - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Adicionar Item de Pedido</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
                    {{ form.quantity|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.unitary_price.id_for_label }}">Preco Unitario</label>
                    {{ form.unitary_price|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.product.id_for_label }}">Produto</label>
                    {{ form.product|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

aulaapp/templates/orders/edit_order_status.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Item de Pedido - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Alterar Status do Pedido</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.status.id_for_label }}">Status</label>
                    {{ form.status|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Alterar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

aulaapp/templates/orders/list_orders.html
{% extends 'base.html' %}

{% block title %}

    Lista de Pedidos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Pedidos</b></h5>
        <div class="row">
            <div class ="col-md-12">
            <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Status</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Preco Total</th>
                    <th scope="col">Itens de pedido</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <th scope="row">
                                {% if order.status == 'Finalizado' or order.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ order.id }}</p>
                                {% else %}
                                    {{ order.id }}
                                {% endif %}
                            </th>
                            <td>
                                {% if order.status == 'Finalizado' or order.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ order.status }}</p>
                                {% else %}
                                    {{ order.status }}
                                {% endif %}
                            </td>
                            <td>
                                {% for client in clients %}
                                    {% if order.client_id == client.id %}
                                        {% if order.status == 'Finalizado' or order.status == 'Cancelado' %}
                                            <p style="color:darkgray;" >{{ client.first_name }} {{ client.last_name }}</p>
                                        {% else %}
                                            {{ client.first_name }} {{ client.last_name }}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}   
                            </td>
                            <td>
                                {% if order.status == 'Finalizado' or order.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >R$ {{ order.total_price }}</p>
                                {% else %}
                                    R$ {{ order.total_price }}
                                {% endif %}
                            </td>
                            <td>
                                {% if order.status == 'Finalizado' or order.status == 'Cancelado' %}
                                    <a href="#" class="btn btn-primary btn-sm disabled">Adicionar itens</a>
                                {% else %}
                                    <a href="{% url 'orders:add_order_item' order.id %}" class="btn btn-primary btn-sm">Adicionar itens</a>
                                {% endif %}
                                <br /><br />
                                {% for order_item in order_items %}
                                    {% if order_item.order_id == order.id %}
                                        Produto: {{ order_item.product}}<br /> 
                                        Quantidade: {{ order_item.quantity}}<br />
                                        Valor Unitario: R$ {{ order_item.unitary_price }}<br />
                                        <a href="{% url 'orders:delete_order_item' order_item.id %}">Excluir Item</a><br /><br />
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'orders:edit_order_status' order.id %}" class="btn btn-danger btn-sm ">Alterar Status</a>
                            </td>
                            <td>
                                <a href="{% url 'orders:delete_order' order.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}