aulaapp/apps/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.list_products, name='list_products'),
    path('adicionar/', views.add_product, name='add_product'),
    path('editar/<int:id_product>/', views.edit_product, name='edit_product'),
    path('excluir/<int:id_product>/', views.delete_product, name='delete_product'),
]

aulaapp/aulaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('redessociais/', include('socialnetworks.urls', namespace='socialnetworks')),
    path('produtos/', include('products.urls', namespace='products')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('pedidos/', include('orders.urls', namespace='orders')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aulaapp/apps/products/models.py
from django.db import models
from categories.models import Category

# Create your models here.

class Product(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=50)
    description = models.TextField('Descricao', max_length=100)
    date_fabrication = models.DateField('Data Fabricacao', auto_now=False, auto_now_add=False) 
    is_active = models.BooleanField('Ativo', default=False)
    photo = models.ImageField('Foto', upload_to='photos')
    doc = models.FileField('Documentos', upload_to='docs')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering =['id']

    def __str__(self):
        return self.name

aulaapp/apps/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('created_on' , 'updated_on',)

aulaapp/apps/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ProductForm
from .models import Product
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/contas/login/')
def add_product(request):
    template_name = 'products/add_product.html'
    context = {}
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('products:list_products')
    form = ProductForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_products(request):
    template_name = 'products/list_products.html'
    products = Product.objects.filter()
    context = {
        'products': products
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_product(request, id_product):
    template_name = 'products/add_product.html'
    context ={}
    product = get_object_or_404(Product, id=id_product)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES,  instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:list_products')
    form = ProductForm(instance=product)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_product(request, id_product):
    product = Product.objects.get(id=id_product)
    product.delete()
    return redirect('products:list_products')

aulaapp/templates/products/add_product.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Produto - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Produto</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Descricao</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.date_fabrication.id_for_label }}">Data de fabricacao</label>
                    {{ form.date_fabrication|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.is_active.id_for_label }}">Ativar</label>
                    {{ form.is_active }}
                </div>
                <div class="form-group">
                    <label for="{{ form.category.id_for_label }}">Categoria</label>
                    {{ form.category|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.photo.id_for_label }}">Foto</label>
                    {{ form.photo|add_class:"form-control-file" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.doc.id_for_label }}">Documentos</label>
                    {{ form.doc|add_class:"form-control-file" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

aulaapp/templates/products/list_products.html
{% extends 'base.html' %}

{% block title %}

    Lista de Produtos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Produtos</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col"><a href="{% url 'products:add_product' %}">Cadastro de novo produto</a></th>
                    <th scope="col">Nome</th>
                    <th scope="col">Descricao</th>
                    <th scope="col">Data de fabricacao</th>
                    <th scope="col">Ativo</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Foto</th>
                    <th scope="col">Documento</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                        <tr>
                            <th scope="row">{{ product.id }}</th>
                            <td>{{ product.name }}</td>
                            <td>{{ product.description }}</td>
                            <td>{{ product.date_fabrication }}</td>
                            <td>
                                {% if product.is_active == True %}
                                    Ativo
                                {% endif %}
                                {% if product.is_active == False %}
                                    Inativo
                                {% endif %}
                            </td>
                            <td>{{ product.category }}</td>
                            <td>
                                <img src="{{ product.photo.url }}" width="50" height="50">
                            </td>
                            <td>
                                <a href="{{ product.doc.url }}" >{{ product.doc.url }}</a>
                            </td>
                            <td>
                                <a href="{% url 'products:edit_product' product.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'products:delete_product' product.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}