aulaapp/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
]

aulaapp/apps/clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.list_clients, name='list_clients'),
    path('adicionar/', views.add_client, name='add_client'),
    path('editar/<int:id_client>/', views.edit_client, name='edit_client'),
    path('excluir/<int:id_client>/', views.delete_client, name='delete_client'),
    path('buscar/', views.search_clients, name='search_clients'),
]

aulaapp/apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('adicionar/<int:id_client>/', views.add_order, name='add_order'),
    path('excluir/<int:id_order>/', views.delete_order, name='delete_order'),
    path('excluir-item/<int:id_order_item>/', views.delete_order_item, name='delete_order_item'),
    path('adicionar-item/<int:id_order>/', views.add_order_item, name='add_order_item'),
    path('editar-status/<int:id_order>/', views.edit_order_status, name='edit_order_status'),
]

aulaapp/apps/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.list_products, name='list_products'),
    path('adicionar/', views.add_product, name='add_product'),
    path('editar/<int:id_product>/', views.edit_product, name='edit_product'),
    path('excluir/<int:id_product>/', views.delete_product, name='delete_product'),
]

aulaapp/aulaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('redessociais/', include('socialnetworks.urls', namespace='socialnetworks')),
    path('produtos/', include('products.urls', namespace='products')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('pedidos/', include('orders.urls', namespace='orders')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aulaapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Aula App{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Aula App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'clients:list_clients' %}">Clientes</a>
                        <a class="dropdown-item" href="{% url 'orders:list_orders' %}">Pedidos</a>
                        <a class="dropdown-item" href="{% url 'products:list_products' %}">Produtos</a>
                        <a class="dropdown-item" href="{% url 'categories:list_categories' %}">Categorias</a>
                        <a class="dropdown-item" href="{% url 'socialnetworks:list_socialnetworks' %}">Redes Sociais</a>
                    </div>
                </li>
            </ul>
            <form action="{% url 'clients:search_clients' %}" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" placeholder="Sobrenome do cliente" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                    </div>
                </li>
            </ul>
        </div>
        {% endif %}
    </nav>

    {% block body %}
    

    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>