aulaapp/apps/clients/urls.py
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.list_clients, name='list_clients'),
    path('adicionar/', views.add_client, name='add_client'),
    path('editar/<int:id_client>/', views.edit_client, name='edit_client'),
    path('excluir/<int:id_client>/', views.delete_client, name='delete_client'),
    path('buscar/', views.search_clients, name='search_clients'),
]

aulaapp/apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('adicionar/<int:id_client>/', views.add_order, name='add_order'),
    path('excluir/<int:id_order>/', views.delete_order, name='delete_order'),
    path('excluir-item/<int:id_order_item>/', views.delete_order_item, name='delete_order_item'),
    path('adicionar-item/<int:id_order>/', views.add_order_item, name='add_order_item'),
    path('editar-status/<int:id_order>/', views.edit_order_status, name='edit_order_status'),
]

aulaapp/aulaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('redessociais/', include('socialnetworks.urls', namespace='socialnetworks')),
    path('produtos/', include('products.urls', namespace='products')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('pedidos/', include('orders.urls', namespace='orders')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aulaapp/apps/clients/models.py
from django.db import models
from django.db import models
from socialnetworks.models import Socialnetwork

# Create your models here.

class Client(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    first_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=100) 
    address = models.CharField('Endereco', max_length=200)   
    cell_phone = models.CharField('Telefone celular', max_length=20)
    email = models.EmailField('E-mail',null=False, blank=False)
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro'),
    )
    gender = models.CharField('Genero', max_length=1, choices=GENDER_CHOICES)
    client_socialnetwork = models.ManyToManyField(Socialnetwork, through='ClientSocialnetwork', blank=True)
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering =['id']

    def __str__(self):
        return self.first_name


class ClientSocialnetwork(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    socialnetwork = models.ForeignKey(Socialnetwork, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de Redes Social'
        verbose_name_plural = 'Itens de Rede Social'
        ordering =['id']

    def __str__(self):
        return self.socialnetwork.name

aulaapp/apps/clients/forms.py
from django import forms
from .models import Client

class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        exclude = ('created_on' , 'updated_on',)

aulaapp/apps/clients/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ClientForm
from .models import Client, Socialnetwork, ClientSocialnetwork
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/contas/login/')
def add_client(request):
    template_name = 'clients/add_client.html'
    context = {}
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('clients:list_clients')
    form = ClientForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_clients(request):
    template_name = 'clients/list_clients.html'
    client_socialnetworks = ClientSocialnetwork.objects.filter()
    socialnetworks = Socialnetwork.objects.filter()
    clients = Client.objects.filter()
    context = {
        'clients': clients,
        'socialnetworks': socialnetworks,
        'client_socialnetworks': client_socialnetworks
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_client(request, id_client):
    template_name = 'clients/add_client.html'
    context ={}
    client = get_object_or_404(Client, id=id_client)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect('clients:list_clients')
    form = ClientForm(instance=client)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_client(request, id_client):
    client = Client.objects.get(id=id_client)
    client.delete()
    return redirect('clients:list_clients')

@login_required(login_url='/contas/login/')
def search_clients(request):
    template_name = 'clients/list_clients.html'
    query = request.GET.get('query')
    client_socialnetworks = ClientSocialnetwork.objects.filter()
    socialnetworks = Socialnetwork.objects.filter()
    clients = Client.objects.filter(last_name__icontains=query)
    context = {
        'clients': clients,
        'socialnetworks': socialnetworks,
        'client_socialnetworks': client_socialnetworks
    }
    return render(request,template_name, context)

aulaapp/templates/clients/add_client.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Cliente - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Cliente</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.first_name.id_for_label }}">Nome</label>
                   {{ form.first_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                  <label for="{{ form.cell_phone.id_for_label }}">Telefone</label>
                  {{ form.cell_phone|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-mail</label>
                    {{ form.email|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.gender.id_for_label }}">Genero</label>
                    {{ form.gender|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.client_socialnetwork.id_for_label }}">Redes sociais</label>
                    {{ form.client_socialnetwork|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

aulaapp/templates/clients/list_clients.html
{% extends 'base.html' %}

{% block title %}

    Lista de Clientes - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Clientes</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'clients:add_client' %}">Cadastro de novo cliente</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col"><a href="{% url 'clients:add_client' %}">Cadastro de novo cliente</a></th>
                    <th scope="col">Nome</th>
                    <th scope="col">Sobrenome</th>
                    <th scope="col">Endereco</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Redes sociais</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for client in clients %}
                        <tr>
                            <th scope="row">{{ client.id }}</th>
                            <td>{{ client.first_name }}</td>
                            <td>{{ client.last_name }}</td>
                            <td>{{ client.address }}</td>
                            <td>{{ client.cell_phone }}</td>
                            <td>{{ client.email }}</td>
                            <td>{{ client.gender }}</td>
                            <td>
                                {% for client_socialnetwork in client_socialnetworks %}
                                    {% if client_socialnetwork.client_id == client.id %}
                                        <li>{{ client_socialnetwork.socialnetwork }}</li>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'clients:edit_client' client.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'clients:delete_client' client.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                            <td>   
                                 <a href="{% url 'orders:add_order' client.id %}" class="btn btn-danger btn-sm ">Pedir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}